version: "3.5"

services:
  nginx:
      image: nginx:1.17
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/html:/usr/share/nginx/html
        - ./nginx/conf.d:/etc/nginx/conf.d
        - /www/:/www/
        - /home/:/home/
      environment:
        - TZ=Asia/Shanghai
#      expose:
#        - "9000"
#        - "6379"
#        - "3306"
#        - "9200"
#        - "9300"
      extra_hosts:
      - "a.net:10.3.1.100"
      - "b.net:10.3.1.100"
      networks:
        swoole:
            aliases:
              - nginx
        swoole-h:
          ipv4_address: 10.3.1.100
          aliases:
          - nginx
  php:
      build: ./php
      container_name: php
#      ports:
#        - "9000:9000"
      extra_hosts:
      - "a.net:10.3.1.100"
      - "b.net:10.3.1.100"
      volumes:
        - /www/:/www/
        - /home/:/home/
      environment:
        - TZ=Asia/Shanghai
      networks:
        swoole:
            aliases:
              - php
        swoole-h:
          ipv4_address: 10.3.1.110
          aliases:
          - php
  phpcli:
      build: ./php-cli
      container_name: php-cli
      command: php /demo/demo.php
#      expose:
#        - "9501"
#      ports:
#        - "9501:9501"
      extra_hosts:
      - "a.net:10.3.1.100"
      - "b.net:10.3.1.100"
      volumes:
        - /www/:/www/
        - /home/:/home/
        - ./php-cli/demo:/demo:ro
      environment:
        - TZ=Asia/Shanghai
      networks:
              swoole:
                  aliases:
                    - phpcli
              swoole-h:
                ipv4_address: 10.3.1.120
                aliases:
                - phpcli
  mysql:
      build: ./mysql
      container_name: mysql
      hostname: mysql
      ports:
        - "3306:3306"
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - /tmp/:/tmp/
        - ./mysql/data:/var/lib/mysql
      networks:
        swoole:
            aliases:
              - mysql
  redis:
      build: ./redis
      container_name: redis
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - /www/:/www/
        - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - TZ=Asia/Shanghai
      networks:
              swoole:
                  aliases:
                    - redis
  elasticsearch:
    image: foxiswho/elk:elasticsearch-7.2.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt:ro
      #词库 7.1.1 默认安装了
      - ./elasticsearch/plugins/analysis-ik/config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/plugins/analysis-ik/config/IKAnalyzer.cfg.xml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      # elasticsearch/data 数据存储目录,记得本目录设置 777 可写权限，否则启动不成功
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      swoole:
        aliases:
          - elasticsearch
  logstash:
    image: foxiswho/elk:logstash-7.2.0
    container_name: logstash
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/logs:/usr/share/logstash/logs
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:rw
#    ports:
#      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      swoole:
        aliases:
          - logstash
    depends_on:
      - elasticsearch
  kibana:
    image: foxiswho/elk:kibana-7.2.0
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/configkibana.yml
    ports:
      - "5601:5601"
    networks:
      swoole:
        aliases:
          - kibana
    depends_on:
      - elasticsearch

networks:
  swoole:
    name: swoole
    driver: bridge
  swoole-h:
    name: swoole-h
    driver: macvlan
    ipam:
      driver: default
      config:
      - subnet: 10.3.1.0/24
