version: '3.5'

services:
  nginx:
      image: nginx:1.17
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/html:/usr/share/nginx/html
        - ./nginx/conf.d:/etc/nginx/conf.d
        - /Volumes:/Volumes
        - /Users:/Users
      environment:
          - TZ=Asia/Shanghai
#      expose:
#        - "9000"
#        - "6379"
#        - "3306"
#        - "9200"
#        - "9300"
      extra_hosts:
            - "a.net:127.0.0.1"
            - "b.net:127.0.0.1"
      networks:
              swoole:
                  aliases:
                    - nginx
              swoole-h:
                  ipv4_address: 10.3.1.100
                  aliases:
                    - nginx
      depends_on:
            - php
  php:
      build: ./php
      container_name: php
      expose:
        - "9000"
      volumes:
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - /tmp/:/tmp/
      environment:
        - TZ=Asia/Shanghai
      extra_hosts:
        - "a.net:10.3.1.100"
        - "b.net:10.3.1.100"
      networks:
              swoole:
                  aliases:
                    - php
              swoole-h:
                  ipv4_address: 10.3.1.110
                  aliases:
                    - php
      depends_on:
            - mysql
  phpcli:
      build: ./php-cli
      container_name: php-cli
      command: php /demo/demo.php
#      expose:
#        - "9501"
#      ports:
#        - "9501:9501"
      environment:
        - TZ=Asia/Shanghai
      extra_hosts:
      - "a.net:10.3.1.100"
      - "b.net:10.3.1.100"
      volumes:
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - ./php-cli/demo:/demo:ro
        - /tmp/:/tmp/
      #working_dir: /Volumes/
      networks:
              swoole:
                  aliases:
                    - phpcli
              swoole-h:
                  ipv4_address: 10.3.1.120
                  aliases:
                  - phpcli
  mysql:
      build: ./mysql
      container_name: mysql
      hostname: mysql
      ports:
        - "3306:3306"
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - /tmp/:/tmp/
        #- /my/own/datadir:/var/lib/mysql
      networks:
                  swoole:
                      aliases:
                        - mysql
                  swoole-h:
                    ipv4_address: 10.3.1.200
                    aliases:
                    - mysql
  redis:
      build: ./redis
      container_name: redis
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      environment:
        - TZ=Asia/Shanghai
      volumes:
        - /Users/:/Users/
        - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
                  swoole:
                      aliases:
                        - redis
  elasticsearch:
    image: foxiswho/elk:elasticsearch-7.2.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt:ro
      #词库 7.1.1 默认安装了
      - ./elasticsearch/plugins/analysis-ik/config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/plugins/analysis-ik/config/IKAnalyzer.cfg.xml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      # elasticsearch/data 数据存储目录,记得本目录设置 777 可写权限，否则启动不成功
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      swoole:
        aliases:
          - elasticsearch
  logstash:
    image: foxiswho/elk:logstash-7.2.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:rw
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      swoole:
        aliases:
          - logstash
    depends_on:
      - elasticsearch
  kibana:
    image: foxiswho/elk:kibana-7.2.0
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/configkibana.yml
    ports:
      - "5601:5601"
    networks:
      swoole:
        aliases:
          - kibana
    depends_on:
      - elasticsearch

networks:
  swoole:
    name: swoole
    driver: bridge
  swoole-h:
    name: swoole-h
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.3.1.0/24